name: Azure ARM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main
        
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./Resources/main.bicep
          deploymentMode: Incremental
          parameters: 'anonymousApiKey=${{ secrets.BICEP_ANONYMOUS_API_KEY }} authorizedApiKey=${{ secrets.BICEP_AUTHORIZED_API_KEY }}'
          additionalArguments: '--what-if --rollback-on-error'
          failOnStdErr: false
